#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here

module load samtools/0.1.19 bowtie2 boost tophat
tophat -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 /project/bf528/project_2/reference/mm9 /projectnb/bf528/users/tinman/Project2/data_curator/PO_1_1.fastq /projectnb/bf528/users/tinman/Project2/data_curator/PO_1_2.fastq

samtools flagstat /projectnb/bf528/users/tinman/Project2/Programmer/sample1/P0_1_tophat/accepted_hits.bam


module load R
module load python3
module load python3 samtools rseqc

samtools index /projectnb/bf528/users/tinman/Project2/Programmer/sample1/P0_1_tophat/accepted_hits.bam

geneBody_coverage.py -r /project/bf528/project_2/reference/annot/mm9.bed -i /projectnb/bf528/users/tinman/Project2/Programmer/sample1/P0_1_tophat/accepted_hits.bam -o output
inner_distance.py -r /project/bf528/project_2/reference/annot/mm9.bed -i /projectnb/bf528/users/tinman/Project2/Programmer/sample1/P0_1_tophat/accepted_hits.bam -o output1
bam_stat.py -i /projectnb/bf528/users/tinman/Project2/Programmer/sample1/P0_1_tophat/accepted_hits.bam 
echo "Job finished: $(date +%F)"